### PR TITLE
Adding 2nd tracker just for rsync target requests

### PR DESCRIPTION
**Pull request by marked**
to offload extraneous traffic from main tracker

### CODE REVIEW

**Comment by marked** [comment]
This is needed because tracker is the bottleneck now for google+ project

**Comment by PhirePhly** [comment]
Is the plan to manually make sure the active targets list is the same on both trackers?

**Comment by marked** [comment]
No, the plan is to only manage google+ trackers in the interface that matters to workers

**Comment by km09** [comment]
This is likely not needed, was an idea for load-shedding for the main tracker.

**Comment by marked** [comment]
To keep this thread up to date.  This is Plan B.

Plan A is to edit:
https://github.com/ArchiveTeam/tracker-config/blob/master/nginx/nginx.conf
or
https://github.com/ArchiveTeam/tracker-config/blob/master/nginx-1.7/nginx.conf
But we don't know who has rights to that machine.

**Comment by PhirePhly** [comment]
Alright. Let me more clearly explain my concern then. During the roll-out of this patch, you're going to have crawlers running both the old and the new code, so queries will be going to both trackers for what rsync target to use. During roll-out, we will need to manually keep the two sets of rsync targets on the two trackers in sync, particularly since the non-warrior grabbers don't auto-update their code.

**Pull request closed without merging**
